### ISSUE TITLE
Publish latest to npm

### ISSUE THREAD

**Issue by jesucarr** [thallium205/xero#10]
the latest version published in npm (0.0.7) doesn't have the latest from github

**Comment by kjgorman** [comment]
:+1: it would be nice if this could happen as the open bound on `easyxml` has allowed a breaking change to slip in -- so the module is unusable currently.

**Comment by andrew-wharton** [comment]
Please publish the fixed version to npm. This library is actively being promoted as the 'pseudo-official' node integration library (http://developer.xero.com/code-samples/libraries/node-js/) so please *at least* make sure it works.

If you don't have time or motivation to maintain the library, please consider handing it over to someone else who does.

**Comment by ronanq** [comment]
Hi

We just got the heads up on this.
We (Xero) are happy to step in and help somehow if we can - you can reach me through api(at)xero.com - just mention Node and Ronan and it will find me.

**Comment by thallium205** [comment]
Sorry all I've been quite sick recently.  I will add some contributors so
it can be maintained.

**Comment by thallium205** [comment]
Everyone in this thread is now a collaborator.  Sorry again.

**Comment by thallium205** [comment]
I will push to npm now.

**Comment by thallium205** [comment]
All updated all.  Apologies.

**Comment by jesucarr** [comment]
hey thanks for adding collaborators. However you would still need to be alert to publish to npm. You can also add some collaborators there as well. My npm username is the same as here: jesucarr.
