### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by awb99** [thallium205/xero#22]
When there is an error with the request, then the error should be forewarded to the client. I suggest to paste the complete xml error message that comes from xero. 

Otherwise, one never knows the reason WHY something went wrong.

**Comment by andrew-wharton** [comment]
Hi @awb99,

This seems to be an issue with the example. This library is simply a wrapper around the Xero API, so it's your application's responsibility to handle how it handles errors from Xero API.

I'll close this as I'm going to update the example in the README.
