### ISSUE TITLE
easyxml@1.0.0

### ISSUE THREAD

**Issue by tlhunter** [thallium205/xero#6]
You'll want to update your package.json to load a specific version of easyxml (e.g. 0.1.0 instead of *) as the latest version breaks API compatibility.

**Comment by umairsiddique** [comment]
#7

**Comment by kundu** [comment]
```javascript
{
  "name": "xero",
  "version": "0.0.5",
  "dependencies": {
    "oauth": "0.9.10",
    "easyxml": "*",
    "xml2js": "*"
  }
}
```
 
The issue is still there.

**Comment by sebgie** [comment]
@thallium205 could you push the updated version to npm, please? The published version is not working atm and #7 would fix it.

**Comment by tengis** [comment]
@thallium205 Could you update npm version? 
npm install command still downloads old version

**Comment by thallium205** [comment]
Updated! Sorry for the delay.

**Comment by sebgie** [comment]
Thanks :+1:
